server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: 'http://localhost:8085'
          predicates:
            - Path=/api/**
        - id: post_service
          uri: 'http://localhost:8086'
          predicates:
            - Path=/posts/**